print("how old are you?", end=' ')
age = input()
print("how tall are you?", end=' ')
height = input()
print("How much do you weigh?", end=' ')
weight = input()
print(f"So, you're {age} old, {height} tall and {weight} heavy.")
print("tell me a number", end=' ')
number = int(input())
print("tell me another number but this time it should be more than 100", end=' ')
number_2 =int(input())
print("sum of the number you told me is", number + number_2)
